language: rust
cache: cargo

env:
  global:
    - RUSTFLAGS=-Dwarnings

branches:
  only:
    - master

matrix:
  include:
    # Lint and test on branch pushes and PRs
    - env: TASK=lint
      rust: stable
      if: type != cron
    - env: TASK=test
      rust: stable
      if: type != cron
    - env: TASK=test
      rust: beta
      if: type != cron
    - env: TASK=test
      rust: nightly
      if: type != cron

    # Update the list on crons
    - env: TASK=update
      rust: stable
      if: type = cron

  # Don't block CI if a nightly is faulty
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script: |
  if [[ $TASK = "lint" ]]; then
      rustup component add rustfmt-preview
      rustup component add clippy-preview
  fi

script: |
  if [[ $TASK = "lint" ]]; then
      cargo fmt -- --check && cargo clippy
  elif [[ $TASK = "test" ]]; then
    cargo build --release && cargo test --release
  elif [[ $TASK = "update" ]]; then
    ./ci-update.sh
  fi

notifications:
  email: false
