[package]
name = "rust-repos"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]

[dependencies]
failure = "0.1.2"
reqwest = "0.8.7"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
log = "0.4.3"
env_logger = "0.5.11"
csv = "1.0.1"
ctrlc = "3.1.1"
crossbeam-utils = "0.5.0"
failure_derive = "0.1.2"
