---

name: Test
on:
  pull_request:
  push:
    paths:
      # Avoid running CI when the only changes were in the `data/` directory
      - "!data/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust (stable)
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check Clippy
        run: cargo clippy -- -Dwarnings

      - name: Run tests
        run: cargo test
